// Shared TypeScript interfaces for all viz components.
// Every component in components/viz/ imports from here.
// Do not duplicate these inline — keep the source of truth here.

/**
 * A row of `fixtures/corridor-rents.json` — owned by the cre-swfl
 * `corridor_profiles` table. Regenerated by `npm run fixtures:corridors`.
 * Rent + vacancy + absorption only. Permits / centroid data lives in
 * separate domain-owned fixtures (see below).
 */
export interface CorridorEntry {
  id: string;
  name: string;
  submarket: string;
  nnn_asking_rent_per_sqft: number | null;
  vacancy_pct: number | null;
  absorption_sqft: number | null;
}

/**
 * A row of `fixtures/corridor-permits.json` — owned by the permits-swfl pack
 * sidecar (Stage 4 emit). Lee-only by structural reality; Collier corridors
 * have no entry here. `corridor_id` is the centroid namespace; bridge to
 * cre-swfl slugs via `refinery/lib/corridor-aliases.mts`.
 */
export interface CorridorPermitsEntry {
  corridor_id: string;
  headline_z: number;
  n_current: number;
  last_refined_at: string;
}

/**
 * A row of `fixtures/corridor-centroids.json` — hand-authored Lee corridor
 * centroids. Same namespace as CorridorPermitsEntry.corridor_id; the alias
 * table maps cre-swfl slugs → centroid corridor_ids.
 */
export interface CorridorCentroidEntry {
  corridor_id: string;
  corridor_label: string;
  center_lat: number;
  center_lon: number;
  submarket: string;
}

/**
 * Merged shape consumed by the embed-time viz components. Produced once by
 * `app/embed/charts/page.tsx` (single canonical join site) — walks the
 * alias table and joins rent rows with their optional permit + centroid
 * data. `permits === null` means "known no-coverage" (Collier corridor);
 * downstream code renders the "no permits coverage" badge.
 */
export interface JoinedCorridorRow {
  id: string;
  name: string;
  submarket: string;
  nnn_asking_rent_per_sqft: number | null;
  vacancy_pct: number | null;
  absorption_sqft: number | null;
  permits: CorridorPermitsEntry | null;
  centroid: CorridorCentroidEntry | null;
}

export interface ZHVIMonth {
  month: string; // "YYYY-MM"
  cape_coral: number | null;
  fort_myers: number | null;
  naples: number | null;
}

// Non-nullable version of ZHVIMonth used for chart rendering (nulls filtered before passing in).
export interface ZHVITrendEntry {
  month: string; // "YYYY-MM"
  cape_coral: number;
  fort_myers: number;
  naples: number;
}

// Generic pivoted-view city series — the wide { month, <city>… } shape shared by
// every data_lake.*_pivoted view (ZHVI home values, ZORI rents, …) on /charts.
// Same structure as ZHVIMonth/ZHVITrendEntry, named neutrally so a ZORI panel
// isn't typed as "ZHVI". Add a city here only if every pivoted view exposes it.
export type PivotedCityMonth = ZHVIMonth; // raw view row; a city may be null for a month
export type MetroTrendEntry = ZHVITrendEntry; // chart-ready row (all cities present)

// A generic chart row: a month label plus one or more numeric series values.
// Superset of MetroTrendEntry (the 3-metro shape) so one chart component can
// render both the pivoted-view metros and a single-series feed (e.g. airport
// passengers). See app/_design/07-charts-and-dataviz.md §6.
export interface ChartRow {
  month: string; // "YYYY-MM"
  [seriesKey: string]: number | string;
}

// One plotted line: which data key to read, and how to label/color/dash it.
// `dash` is an SVG strokeDasharray ("" = solid) — the colorblind-safe second
// channel alongside color (the gulf series colors are near-iso-luminant, so
// color alone is insufficient per WCAG 1.4.1). See 07-charts-and-dataviz.md §2.
export interface ChartSeriesDef {
  key: string;
  label: string;
  color: string;
  dash?: string;
}

export interface ZORIEntry {
  zip: string;
  city: string;
  county: string;
  trend: { month: string; rent: number }[];
}

export interface KeyMetric {
  label: string;
  value: string;
  trend: "up" | "down" | "flat";
  change_pct: number;
}

export interface BrainOutput {
  id: string;
  conclusion: string;
  confidence: number; // 0–1
  freshness_token: string;
  updated_at: string;
  sources_count: number;
  key_metrics: KeyMetric[];
  caveats: string[];
}

export interface PermitMonth {
  month: string; // "YYYY-MM"
  zscore: number;
}

export interface PermitHeatmapRow {
  corridor: string;
  months: PermitMonth[];
}

export interface VizStats {
  corridors_tracked: number;
  sqft_analyzed: number;
  data_sources: number;
  swfl_zips: number;
  flood_records: number;
  brain_confidence: number;
}

/**
 * One corridor's seasonality reading. Produced by cre-swfl
 * (`seasonal_index` from `CorridorNormalized`). Used by `SeasonalRadialChart`.
 */
export interface SeasonalRadialEntry {
  /** Display name of the corridor (e.g. "US 41 - Downtown Fort Myers"). */
  corridor: string;
  /** Seasonality index: 0 = no seasonality, 1 = extreme seasonality. */
  seasonal_index: number;
}
